services:
  db:
    image: postgres:15
    container_name: test_ISI_toDoList
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_ISI_toDoList
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/.env
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      
volumes:
  db-data:
